witb5-django-ecommerce/ecomm/ecomm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', include('toko.urls', namespace='toko')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

witb5-django-ecommerce/ecomm/toko/urls.py
from django.urls import path
from . import views

app_name = 'toko'

urlpatterns = [
     path('', views.HomeListView.as_view(), name='home-produk-list'),
     path('product/<slug>/', views.ProductDetailView.as_view(), name='produk-detail'),
     path('checkout/', views.CheckoutView.as_view(), name='checkout'),
     path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
     path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
#     path('update_qty/<slug>/', views.update_qty, name='update-qty'),
     path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
     path('payment/<payment_method>', views.PaymentView.as_view(), name='payment'),
     path('paypal-return/', views.paypal_return, name='paypal-return'),
     path('paypal-cancel/', views.paypal_cancel, name='paypal-cancel'),
     path('stripe-return/', views.stripe_return, name='stripe-return'),
     path('stripe-cancel/', views.stripe_cancel, name='stripe-cancel'),
     path('kontak/', views.KontakView.as_view(), name='kontak'),
     path('search', views.ProdukSearchView.as_view(), name='search'),
]

witb5-django-ecommerce/ecomm/toko/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey

PILIHAN_RATED = (
    ('1', 'satu'),
    ('2', 'dua'),
    ('3', 'tiga'),
    ('4', 'empat'),
    ('5', 'lima')
)

PILIHAN_KATEGORI = (
    ('LE', 'Low-End'),
    ('MR', 'Mid-Range'),
    ('FS', 'Flagship')
)

PILIHAN_LABEL = (
    ('NEW', 'primary'),
    ('SALE', 'info'),
    ('BEST', 'danger'),
)

PILIHAN_PEMBAYARAN = (
    ('P', 'Paypal'),
    ('S', 'Stripe'),
)

User = get_user_model()

#class Category(MPTTModel):
#    name=models.CharField(max_length=50)
#    slug=models.SlugField(max_length=50, unique=True, help_text='Uniue Value product page url, created from name')
#    is_active=models.BooleanField(default=True)
#    created_at=models.DateTimeField(auto_now_add=True)
#    updated_at=models.DateTimeField(auto_now=True)
#    parent=TreeForeignKey('self',on_delete=models.CASCADE,null=True,blank=True, related_name='children')

#    class MPTTMeta:
#        order_insertion_by=['name']

class Category(models.Model):
    nama_kategori = models.CharField(max_length=150, null=False, blank=False)
    slug = models.SlugField(max_length=150, null=False, blank=False)
    deskripsi = models.TextField()
    gambar_category = models.ImageField(upload_to='product_pics')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.nama_kategori
    
    class Meta:
        verbose_name_plural = "categories"
    
    def get_absolute_url(self):
        return reverse("toko:kategori", kwargs={
            "slug": self.slug
            })

class ProdukItem(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=True, null=False)
    nama_produk = models.CharField(max_length=100)
    harga = models.FloatField()
    harga_diskon = models.FloatField(blank=True, null=True)
    slug = models.SlugField(unique=True)
    deskripsi = models.TextField()
    spesifikasi = models.TextField(default=False)
    gambar = models.ImageField(upload_to='product_pics')
    gambar_1 = models.ImageField(upload_to='product_pics', default=False)
    gambar_2 = models.ImageField(upload_to='product_pics', default=False)
    gambar_3 = models.ImageField(upload_to='product_pics', default=False)
    label = models.CharField(choices=PILIHAN_LABEL, max_length=4)
    kategori = models.CharField(choices=PILIHAN_KATEGORI, max_length=2)
    is_active = models.BooleanField(default=True)
    rated = models.CharField(choices=PILIHAN_RATED, max_length=10, default=False)


    def __str__(self):
        return f"{self.nama_produk} - ${self.harga}"

    def get_absolute_url(self):
        return reverse("toko:produk-detail", kwargs={
            "slug": self.slug
            })

    def get_add_to_cart_url(self):
        return reverse("toko:add-to-cart", kwargs={
            "slug": self.slug
            })
    
    def get_remove_from_cart_url(self):
        return reverse("toko:remove-from-cart", kwargs={
            "slug": self.slug
            })
    
class OrderProdukItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    produk_item = models.ForeignKey(ProdukItem, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.produk_item.nama_produk}"

    def get_total_harga_item(self):
        return self.quantity * self.produk_item.harga
    
    def get_total_harga_diskon_item(self):
        return self.quantity * self.produk_item.harga_diskon

    def get_total_hemat_item(self):
        return self.get_total_harga_item() - self.get_total_harga_diskon_item()
    
    def get_total_item_keseluruan(self):
        if self.produk_item.harga_diskon:
            return self.get_total_harga_diskon_item()
        return self.get_total_harga_item()
    
    def get_total_hemat_keseluruhan(self):
        if self.produk_item.harga_diskon:
            return self.get_total_hemat_item()
        return 0


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    produk_items = models.ManyToManyField(OrderProdukItem)
    tanggal_mulai = models.DateTimeField(auto_now_add=True)
    tanggal_order = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    alamat_pengiriman = models.ForeignKey('AlamatPengiriman', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

     
    def get_total_harga_order(self):
        total = 0
        for order_produk_item in self.produk_items.all():
            total += order_produk_item.get_total_item_keseluruan()
        return total
    
    def get_total_hemat_order(self):
        total = 0
        for order_produk_item in self.produk_items.all():
            total += order_produk_item.get_total_hemat_keseluruhan()
        return total

class AlamatPengiriman(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    alamat_1 = models.CharField(max_length=100)
    alamat_2 = models.CharField(max_length=100)
    negara = models.CharField(max_length=100)
    kode_pos = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.user.username} - {self.alamat_1}"

    class Meta:
        verbose_name_plural = 'AlamatPengiriman'

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
    payment_option = models.CharField(choices=PILIHAN_PEMBAYARAN, max_length=1)
    charge_id = models.CharField(max_length=50)

    def __self__(self):
        return self.user.username
    
    def __str__(self):
        return f"{self.user.username} - {self.payment_option} - {self.amount}"
    
    class Meta:
        verbose_name_plural = 'Payment'

witb5-django-ecommerce/ecomm/ecomm/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>

    <title>Samsung Indonesia{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title> Transparent Navbar </title>
    <!--bootstrap 5 css link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  
    <!-- Samsung icon -->
    <link rel="icon" href="https://www.samsung.com/etc.clientlibs/samsung/clientlibs/consumer/global/clientlib-common/resources/images/gnb-desktop-120x32.png" height=10/>
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
  </head>
  <body>
    
    {% include 'navbar.html' %}
 
    {% block content %}
    {% endblock content %}
    
    {% include 'footer.html' %}
  
    {% include 'scripts.html' %}

    {% block scripts %}
    {% endblock scripts %}

  </body>
</html>

witb5-django-ecommerce/ecomm/ecomm/templates/category.html
{% extends "base.html" %}

{% block content %}

{% include "carousel.html" %}

<main>
    <div class="container">

      <h1>{{ cats }}</h1>
<ul>
      {% for produk in category_produk %}
      <li><a href="{% url 'home-produk-list' %}">{{ produk.nama_produk }}></a></li>
      - {{ produk.kategori }}
      {% endfor %}
</ul>

        <!-- Link Kategori --> 
    </div>
</main>
<!--Main layout--> 

{% endblock content %}

witb5-django-ecommerce/ecomm/ecomm/templates/contentnavbar.html
{% load cart_template_tags %}

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
    <!-- Container wrapper -->
    <div class="container">    
        <!-- Toggle button -->
        <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent1"
        aria-controls="navbarSupportedContent1"
        aria-expanded="false"
        aria-label="Toggle navigation"
        >
        <i class="fas fa-bars"></i>
        </button>
    
        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">      
            <!-- Navbar brand -->
            <!--Logo-->
            <a class="navbar-brand mr-0 mr-md-2" href="/">
                <img
                src="https://www.samsung.com/etc.clientlibs/samsung/clientlibs/consumer/global/clientlib-common/resources/images/gnb-desktop-120x32.png"
                height="25"
                alt="samsung Logo"
                />
            </a>
            <!-- Left links -->
            <div class="navbar-nav-scroll" id="navbarSupportedContent1">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <!--Home-->
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <!--Categories-->
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Categories
                      </a>
                      <ul class="dropdown-menu active">
                        <li><a class="dropdown-item" href="/">Flagship</a></li>
                        <li><a class="dropdown-item" href="/">Mid-Range</a></li>
                        <li><a class="dropdown-item" href="/">Low-End</a></li>
                      </ul>
                    </li>
                    <!--Checkout-->
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'toko:checkout' %}">Checkout</a>
                    <!--Contact Us-->
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'toko:kontak' %}">Contact us</a>
                    </li>                                        
                </ul>
            </div>
            <!-- Right links -->      
            </div>
            <!-- Collapsible wrapper -->
            
            <!-- Right elements -->
            <div class="d-flex align-items-center">            
                    <!-- Icon -->
                    <!--Search-->
                    <div class="input-group rounded me-2">
                    <form class="w-auto py-1" style="max-width: 12rem" method="get" action="{% url 'toko:search' %}">
                        {% csrf_token %}
                        <input type="search" class="form-control rounded-0" placeholder="Search" aria-label="Search" name="q">
                    </form>
                    <!--Cart-->
                {% if request.user.is_authenticated %}
                    </div> 
                    <a class="nav-link me-3" href="{% url 'toko:order-summary' %}">
                        <i class="fas fa-shopping-cart"></i>
                        <span class="badge rounded-pill badge-notification bg-danger">{{ request.user|total_produk_dikeranjang }}</span>
                    </a>
                    <a class="nav-link me-3" href="{% url 'account_logout' %}">
                        <i class="fas fa-right-from-bracket"></i>
                    </a>
                {% else %}
                    <a class="nav-link me-3" href="{% url 'account_login' %}">
                    <i class="fas fa-right-to-bracket"></i>
                {% endif %}
            </div> 
            <!-- Right elements -->
        
    </div>
    <!-- Container wrapper -->
</nav>
    <!-- Navbar -->        
        
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: rgb(0, 0, 0)">
            <!-- Container wrapper -->
            <div class="container-fluid">

                <!-- Navbar brand -->
                <a class="navbar-brand" href="#">Categories:</a>

                <!-- Toggle button -->
                <button
                        class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent2"
                        aria-controls="navbarSupportedContent2"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent2">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!-- Link -->
                        <li class="nav-item active">
                          <a class="nav-link active" href="{% url 'toko:home-produk-list' %}" aria-expanded="false">
                            All
                          </a>
                        </li>
                          
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Flagship
                            </a>
                            <ul class="dropdown-menu active">
                              <li><a class="dropdown-item" href="/product/samsung-galaxy-s23-plus/">Samsung Galaxy S23+</a></li>
                              <li><a class="dropdown-item" href="/product/samsung-galaxy-z-fold-4/">Samsung Galaxy Z Fold4</a></li>
                              <li><a class="dropdown-item" href="/product/samsung-galaxy-z-flip-4/">Samsung Galaxy Z Flip4</a></li>
                            </ul>
                          </li>
                          
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Mid-Range
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="/product/samsung-galaxy-m23-5g/">Samsung Galaxy M23 5G</a></li>
                              <li><a class="dropdown-item" href="/product/samsung-galaxy-m33-5g/">Samsung Galaxy M33 5G</a></li>
                              <li><a class="dropdown-item" href="/product/samsung-galaxy-m53-5g/">Samsung Galaxy M53 5G</a></li>
                            </ul>
                          </li>

                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Low-End
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="/product/samsung-galaxy-m02/">Samsung Galaxy M02</a></li>
                              <li><a class="dropdown-item" href="/product/samsung-galaxy-a03/">Samsung Galaxy A03</a></li>
                              <li><a class="dropdown-item" href="/product/samsung-galaxy-a04/">Samsung Galaxy A04</a></li>
                            </ul>
                          </li>      
                    </ul>
                </div>
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->
        <html lang="en">
          <body>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
          </body>
        </html>        

witb5-django-ecommerce/ecomm/ecomm/templates/footer.html
<footer class="text-center text-white mt-4" style="background-color: #151515">
  <hr class="text-dark">
  <div class="container">
    <footer class="py-5">
      <div class="row">
           
        <div class="col align-self-center">
          <h5>Samsung Indonesia</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="/" class="nav-link p-0 text-muted">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Categories</a></li>
            <li class="nav-item mb-2"><a href="{% url 'toko:checkout' %}" class="nav-link p-0 text-muted">Checkout</a></li>
            <li class="nav-item mb-2"><a href="{% url 'toko:kontak' %}" class="nav-link p-0 text-muted">Contact Us</a></li>
          </ul>
        </div>
  
        <div class="col-4 offset-1">
          <form>
            <h5>Subscribe to our newsletter</h5>
            <p>Monthly digest of whats new and exciting from us.</p>
            <div class="d-flex w-100 gap-2">
              <label for="newsletter1" class="visually-hidden">Email address</label>
              <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
              <a class="btn btn-primary" href='https://gmail.com/' type="button">Subscribe</a>

            </div>
          </form>
        </div>
      </div>
  
      <div class="d-flex justify-content-between py-4 my-4 border-top">
        <p>© 2023 Samsung Indonesia, Inc. All rights reserved.</p>
        <ul class="list-unstyled d-flex">
          <li class="ms-3">
            <a class="btn-link btn-floating btn-lg text-white" href='https://twitter.com/' role="button" target='_blank' data-mdb-ripple-color="dark"><i class="fab fa-twitter"></i></a>
            <a class="btn-link btn-floating btn-lg text-white" href='https://facebook.com/' role="button" target='_blank' data-mdb-ripple-color="dark"><i class="fab fa-facebook-f"></i></a>
            <a class="btn-link btn-floating btn-lg text-white" href='https://google.com/' role="button" target='_blank' data-mdb-ripple-color="dark"><i class="fab fa-google"></i></a>
            <a class="btn-link btn-floating btn-lg text-white" href='https://instagram.com/' role="button" target='_blank' data-mdb-ripple-color="dark"><i class="fab fa-instagram"></i></a>
            <a class="btn-link btn-floating btn-lg text-white" href='https://youtube.com/' role="button" target='_blank' data-mdb-ripple-color="dark"><i class="fab fa-youtube"></i></a>
          </li>
        </ul>
      </div>
    </footer>
  </div>
</footer>

witb5-django-ecommerce/ecomm/ecomm/templates/home.html
{% extends 'base.html' %}

{% block content %}

{% include 'carousel.html' %}

<!--Main layout-->
<main>
    <div class="container">

{% include 'contentnavbar.html' %}

        <!-- Products -->
        <section>
            <div class="text-center">
              <div class="row">
                
                {% for pItem in object_list %} <!-- dari mana sumber objek_list? -->
                <div class="col-lg-3 col-md-6 mb-4">
                  <div class="card">
                    <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                      data-mdb-ripple-color="light">
                      <img src="{{ pItem.gambar.url }}"
                        class="w-100" />
                      <a href="{{ pItem.get_absolute_url }}"> 
                        <div class="mask">
                          <div class="d-flex justify-content-start align-items-end h-100">
                            <h5><span class="badge bg-{{ pItem.get_label_display }} ms-2">{{ pItem.label }}</span></h5>
                          </div>
                        </div>
                        <div class="hover-overlay">
                          <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                        </div>
                      </a>
                    </div>
                    <div class="card-body">
                      <a href="{{ pItem.get_absolute_url }}" class="text-reset">
                        <h5 class="card-title mb-2">{{ pItem.nama_produk }}</h5>
                      </a>
                      <a href="" class="text-reset ">
                        <p>{{ pItem.get_kategori_display }}</p>
                      </a>
                      <h6 class="mb-3 price">${% if pItem.harga_diskon %}{{ pItem.harga_diskon }}{% else %}{{ pItem.harga }}{% endif %}</h6>
                    </div>
                  </div>
                </div>
                {% empty %}
                  <p>Data Produk belum tersedia</p>
                {% endfor %}

              </div>
            </div>
          </section>
        <!-- End Products -->

        <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-3">
            <ul class="pagination">
                <li class="page-item">
                  {% if page_obj.has_previous %}
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                  {% endif %}
                </li>
                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                <li class="page-item">
                  {% if page_obj.has_next %}
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                  {% endif %}
                </li>
            </ul>
        </nav>
        {% endif %}
        <!-- Pagination -->
    </div>
</main>
<!--Main layout-->
{% endblock content %}

witb5-django-ecommerce/ecomm/ecomm/templates/order_summary.html
{% extends 'base.html' %}

{% block content%}

<!--Main layout-->

<br>
<br>

{% include 'contentnavbar.html' %}

<div class="container">
    <div class="row">
        <div class="col-12 mt-4 mb-4">
            <h1 class="text-center">Order Summary</h1>
        </div>
    </div>
    <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
        <tr>
            <th>#</th>
            <th>Nama Produk</th>
            <th>Harga</th>
            <th>Quantity</th>
            <th>Total Harga</th>
        </tr>
        </thead>
        <tbody>
            {% for pItem in keranjang.produk_items.all %}
            <tr>
                <td scope="row">
                    {{ forloop.counter }}
                </td>
                <td>
                    <a href="{% url 'toko:produk-detail' pItem.produk_item.slug %}">
                        <div class="d-flex align-items-center">
                            <img
                                src="{{ pItem.produk_item.gambar.url }}"
                                alt=""
                                style="width: 45px; height: 45px"
                                class="rounded-circle"
                                />
                            <div class="ms-3">
                            <p class="fw-bold mb-1">{{ pItem.produk_item.nama_produk }}</p>
                            <p class="text-muted mb-0"> {{ pItem.produk_item.deskripsi|truncatewords:10 }}</p>
                            </div>
                        </div>
                    </a>
                </td>
                <td>
                    <div>$
                        {% if pItem.produk_item.harga_diskon %}
                        {{ pItem.produk_item.harga_diskon }}
                        {% else %}
                        {{ pItem.produk_item.harga }}
                        {% endif %}
                    </div>
                </td>
                <td><!-- {{ pItem.quantity }} -->
                    {% csrf_token %}
                    <div class="pull-center">
                        <a href="{% url 'toko:remove-from-cart' pItem.produk_item.slug %}" class="btn btn-light"><i class="fa fa-minus"></i>
                        </a>{{ pItem.quantity }}
                        <a href="{% url 'toko:add-to-cart' pItem.produk_item.slug %}" class="btn btn-light"><i class="fa fa-plus"></i></a>
                    </div>
                    
                    <!-- <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                        <a class="minus-cart btn" pid={{pItem.produk_item.id}}><i class="fas fa-minus"></i></a>
                            <span id="quantity">{{ pItem.quantity }}</span>
                        <a class="plus-cart btn" pid={{pItem.produk_item.id}}><i class="fas fa-plus"></i></a> -->
                </td>
                <td>                
                    {% if pItem.produk_item.harga_diskon %}
                    ${{ pItem.get_total_harga_diskon_item }}
                    <span class="badge badge-danger rounded-pill d-inline">Hemat ${{ pItem.get_total_hemat_item }}</span>
                    {% else %}
                    ${{ pItem.get_total_harga_item }}
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan='5'>Keranjang kosong</td>
            </tr>
            <tr>
                <td colspan="5">
                <a class="btn btn-primary float-end" href="{% url 'toko:home-produk-list' %}">Lanjut belanja</a>
                </td>
            </tr>
            {% endfor %}

            {% if keranjang.get_total_harga_order %}
            <tr>
                <td colspan="4"><b>Total Belanja</b></td>
                <td><b>${{ keranjang.get_total_harga_order }}</b>
                    {% if keranjang.get_total_hemat_order %}
                    <span class="badge badge-danger">Hemat ${{ keranjang.get_total_hemat_order }}</span>
                    {% endif %}
                </td>
            </tr>

            <tr>
                <td colspan="5">
                <a class='btn btn-info float-end ml-2' href="{% url 'toko:checkout' %}">Checkout</a>
                <a class='btn btn-danger' href="{% url 'toko:home-produk-list' %}">Lanjut belanja</a>
                </td>
            </tr>
            {% endif %}
        </tbody>
  </table>
  
    <script
		src="https://code.jquery.com/jquery-3.7.0.min.js"
		integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
		crossorigin="anonymous"></script>

    <script>
        //initialising a variable name data
        
        let data = 0;
        
        //creation of increment function
        function increment() {
            data = data + 1;
            document.getElementById("increment-btn").innerText = data;
        }
        //creation of decrement function
        function decrement() {
            data = data - 1;
            document.getElementById("decrement-btn").innerText = data;
        }
    </script>
        
</div>
{% endblock content %}